describe('Tests staging and the admin-specific functions', () => {
  beforeEach ( () => {
    cy.visit('http://localhost:3000/Hjem')
    cy.get('[data-cy="hamburgerMenu"]').click()
    cy.get('[data-cy="loggin"]').click()
    cy.get('[data-cy="email"]').type('admin@trondheim.kommune.no')
    cy.get('[data-cy="password"]').type('admin')
    cy.get('[data-cy="logginButton"]').click()
    cy.wait(2000)
  })
  
  after( () => {
    cy.visit('http://localhost:3000/Hjem')
    cy.wait(1000)
    cy.get('[data-cy="search"]').click()
    cy.contains("EksProblem").click()
    cy.wait(1000)
    cy.get('[data-cy="editIcon"]').click()
    cy.wait(1000)
    cy.get('[data-cy="system"]').click().get('[data-cy = "BlueGarden"]').click()
    cy.get('[data-cy="categorizeSpesProblem"]').should("be.visible").click()
    cy.contains("Prioritization").click()
    cy.wait(1000)
    cy.get('[data-cy="categorizeDataproduct"]').should("be.visible").click()
    cy.contains("Tool").click()
    cy.wait(1000)
    cy.get('[data-cy="categorizeAccesibleData"]').should("be.visible").click()
    cy.contains("CitizenData").click()
    cy.wait(1000)
    cy.get('[data-cy="deleteProblem"]').wait(1000).click();
    cy.wait(1000)
    cy.get('[data-cy="confirmDelete"]').click();
    cy.wait(2000)
  })
  
  it('Approves a problem and checks that it is added correctly', () => {
    cy.get('[data-cy="newProblem"]').click()
    cy.get('[data-cy="title"]').should("be.visible").type("EksProblem")
    cy.get('[data-cy="system"]').click().get('[data-cy = "Visma"]').click()
    cy.get('[data-cy="spesificProblem"]').should("be.visible").type('TESTUS EXAMPLUS')
    cy.get('[data-cy="dataProduct"]').should("be.visible").type('Graph')
    cy.get('[data-cy="accesibleData"]').should("be.visible").type('Excel ark')
    cy.get('[data-cy="definedAction"]').should("be.visible").type('LOREM TESTUM')
    cy.get('[data-cy ="send"]').click()
    cy.visit('http://localhost:3000/Hjem')
    cy.get('[data-cy="evaluateProblem"]').click()
    cy.wait(2000)
    cy.contains("EksProblem").click()
    cy.get('[data-cy="categorizeSpesProblem"]').should("be.visible").click()
    cy.contains("Prioritization").click()
    cy.get('[data-cy="categorizeDataproduct"]').should("be.visible").click()
    cy.contains("Tool").click()
    cy.get('[data-cy="categorizeAccesibleData"]').should("be.visible").click()
    cy.contains("CitizenData").click()
    cy.get('[data-cy="approveProblem"]').click()
    cy.get('[data-cy ="nestaLogo"]').click()
    cy.get('[data-cy="search"]').click()
    cy.contains("EksProblem").should("be.visible")
  })
  it("Creates a new user", () => {
    cy.get('[data-cy="hamburgerMenu"]').click()
    cy.get('[data-cy="newUser"]').click()
    cy.get('[data-cy="affiliation"]').click()
    cy.get('[data-cy="Malvik kommune"]').click()
    cy.get('[data-cy="email"]').type("exampleUser"+ Math.floor(Math.random() * 100) +"@Malvik.kommune.no")
    cy.get('[data-cy="tlf"]').type("45596332")
    cy.get('[data-cy="password"]').type("1234")
    cy.get('[data-cy="confirmPassword"]').type("1234")
    cy.get('[data-cy="send"]').click()
    cy.get('[data-cy="sucess"]').should("be.visible")
  })
  

})